"""add knowledge base and entry tables

Revision ID: 8add442aabdb
Revises: 62db3558f632
Create Date: 2026-07-31 13:57:29.214597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8add442aabdb'
down_revision: Union[str, Sequence[str], None] = '62db3558f632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_category', 'knowledge_bases', ['category'], unique=False)
    op.create_index('idx_kb_exam_type', 'knowledge_bases', ['exam_type'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_subject_id'), 'knowledge_bases', ['subject_id'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('source_location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_id'), 'knowledge_entries', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_knowledge_base_id'), 'knowledge_entries', ['knowledge_base_id'], unique=False)
    # 注意：SQLite 不支持 ALTER 添加列/外键/索引，必须使用 batch_alter_table（copy-and-move 策略）；
    # 其他方言（PostgreSQL 等）下 batch 模式等价于直接操作。
    with op.batch_alter_table('knowledge_points') as batch_op:
        batch_op.add_column(sa.Column('content_excerpt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('knowledge_base_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('entry_id', sa.Integer(), nullable=True))
        # 删除冗余索引 idx_knowledge_parent_id：parent_id 已有 index=True 生成的 ix_knowledge_points_parent_id
        batch_op.drop_index('idx_knowledge_parent_id')
        batch_op.create_index(op.f('ix_knowledge_points_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index(op.f('ix_knowledge_points_knowledge_base_id'), ['knowledge_base_id'], unique=False)
        batch_op.create_foreign_key('fk_kp_knowledge_base_id', 'knowledge_bases', ['knowledge_base_id'], ['id'])
        batch_op.create_foreign_key('fk_kp_entry_id', 'knowledge_entries', ['entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_points') as batch_op:
        batch_op.drop_constraint('fk_kp_entry_id', type_='foreignkey')
        batch_op.drop_constraint('fk_kp_knowledge_base_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_knowledge_points_knowledge_base_id'))
        batch_op.drop_index(op.f('ix_knowledge_points_entry_id'))
        batch_op.create_index('idx_knowledge_parent_id', ['parent_id'], unique=False)
        batch_op.drop_column('entry_id')
        batch_op.drop_column('knowledge_base_id')
        batch_op.drop_column('content_excerpt')
    op.drop_index(op.f('ix_knowledge_entries_knowledge_base_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_id'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_knowledge_bases_subject_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_index('idx_kb_exam_type', table_name='knowledge_bases')
    op.drop_index('idx_kb_category', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
