"""add subject_id and created_by to paper_templates

Revision ID: 970225d575c5
Revises: 887b22c2be31
Create Date: 2026-08-11 12:01:31.175452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970225d575c5'
down_revision: Union[str, Sequence[str], None] = '887b22c2be31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 使用 batch 模式：SQLite 不支持 ALTER 添加外键/索引，需要 copy-and-move；
    # 同时为外键显式命名（原实现 create_foreign_key(None) 匿名约束在 downgrade 无法删除）。
    with op.batch_alter_table('paper_templates') as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_paper_templates_subject_id'), ['subject_id'], unique=False)
        batch_op.create_foreign_key('fk_paper_templates_created_by', 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key('fk_paper_templates_subject_id', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_templates') as batch_op:
        batch_op.drop_constraint('fk_paper_templates_created_by', type_='foreignkey')
        batch_op.drop_constraint('fk_paper_templates_subject_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_paper_templates_subject_id'))
        batch_op.drop_column('created_by')
        batch_op.drop_column('subject_id')
    # ### end Alembic commands ###
