"""add paper versions

Revision ID: a10d86a62df7
Revises: 970225d575c5
Create Date: 2026-08-11 12:02:28.489262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10d86a62df7'
down_revision: Union[str, Sequence[str], None] = '970225d575c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('questions_snapshot', sa.JSON(), nullable=True),
    sa.Column('change_log', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_versions_id'), 'paper_versions', ['id'], unique=False)
    op.create_index(op.f('ix_paper_versions_paper_id'), 'paper_versions', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_versions_paper_id'), table_name='paper_versions')
    op.drop_index(op.f('ix_paper_versions_id'), table_name='paper_versions')
    op.drop_table('paper_versions')
    # ### end Alembic commands ###
