"""add paper template marketplace fields

Revision ID: c3b53d81ed6e
Revises: a10d86a62df7
Create Date: 2026-08-11 12:06:55.810452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b53d81ed6e'
down_revision: Union[str, Sequence[str], None] = 'a10d86a62df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_templates', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('paper_templates', sa.Column('shared_with', sa.JSON(), nullable=True))
    op.add_column('paper_templates', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('paper_templates', sa.Column('usage_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_templates', 'usage_count')
    op.drop_column('paper_templates', 'rating')
    op.drop_column('paper_templates', 'shared_with')
    op.drop_column('paper_templates', 'is_public')
    # ### end Alembic commands ###
